language: python
python:
    - 3.4
    - 3.5
    - pypy3

install: 
    -  pip install .
    - "pip install -r requirements-dev.txt"
    -  pip install flake8
    -  pip install coveralls 
    -  pip install astroid
    -  pip install pylint 
before_script:
    - flake8 .
    - pylint --disable=missing-docstring,invalid-name,fixme *.py

script:
    coverage run --source=groups -m py.test
after_success:
    coveralls
