language: python
python:
    - 3.4
    - 3.5
    - pypy3
    - nightly

install: 
    -  pip install .
    - "pip install -r requirements-dev.txt"
    -  pip install flake8
    -  pip install coveralls 
before_script: ./setup.sh

script:
    coverage run --source=groups -m py.test
after_success:
    coveralls
